var SERVER_PORT = 9000;
var INPUT_PORT = 9001;
var STATE_PORT = 9002;
var OPPONENT_PORT = 9003;

module.exports = {
    SERVER_PORT: SERVER_PORT,
    INPUT_PORT: INPUT_PORT,
    STATE_PORT: STATE_PORT
};